### ISSUE TITLE
Pulling local packages

### ISSUE THREAD

**Issue by DCzajkowski** [Naoray/laravel-lab#1]
Hello,
I have a package for Laravel downloaded locally from GitHub. Now I would like to make changes to it locally, see does it work and then push it to the original repo. How would one go about doing this? Can you give an example?

I have tried using this:
```bash
php artisan package:add DCzajkowski/auth-tests /Users/Darek/web/packages/auth-tests
```

But that just creates an entry in the `composer.json` like so:
```json
"repositories": {
    "DCzajkowski/auth-tests": {
        "type": "path",
        "url": "/Users/Darek/web/packages/auth-tests"
    }
}
```
which fails, obviously. Can you even do that with this project?

**Comment by DCzajkowski** [comment]
Ok, never mind. You need this:
```
"require": {
    // ...
    "DCzajkowski/auth-tests": "*"
}
```

It would be cool if this was handled automatically when there is no dev-master ;)

**Comment by DCzajkowski** [comment]
It would be cool if this was handled automatically ;)

**Comment by Naoray** [comment]
This is handled automatically. You just have to use the command with the right arguments. Try `php artisan package:add auth-tests /Users/Darek/web/packages/auth-tests --vendor=DCzajkowski`

**Comment by DCzajkowski** [comment]
Oh, nice. Thanks ☺️
